# Generated by Django 2.0.6 on 2018-06-27 02:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Frame',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('frame_number', models.PositiveIntegerField()),
                ('frame_type', models.CharField(choices=[('STRIKE', 'STRIKE'), ('SPARE', 'SPARE'), ('OPEN', 'OPEN'), ('ROLLING', 'ROLLING')], default='ROLLING', max_length=7)),
            ],
        ),
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_ongoing', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='players', to='scoring.Game')),
            ],
        ),
        migrations.CreateModel(
            name='Roll',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pins_knocked_down', models.IntegerField()),
                ('roll_number', models.IntegerField()),
                ('frame', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rolls', to='scoring.Frame')),
            ],
        ),
        migrations.AddField(
            model_name='frame',
            name='player',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='frames', to='scoring.Player'),
        ),
    ]
